### ISSUE TITLE
WebPageDemo.ipynb error

### ISSUE THREAD

**Issue by beddows** [jerryjliu/gpt_index#319] opened 2023-01-27 16:35 UTC
In the file examples/data_connectors/WebPageDemo.ipynb, the "Using RssReader" demo throws the error: AttributeError: 'list' object has no attribute 'split'

Any thoughts on what this could be?

**Comment by simonManydata** [comment] 2023-01-29 19:37
Can you share the trace of the error message?

**Comment by jerryjliu** [comment] 2023-01-29 22:32
@beddows is it fixed now? the rss reader has been updated

**Comment by beddows** [comment] 2023-01-30 14:43
@jerryjliu @simonManydata Still getting the error - trace attached

[WebPageDemo_RssReader_attributeError.txt](https://github.com/jerryjliu/gpt_index/files/10536772/WebPageDemo_RssReader_attributeError.txt)

**Comment by jerryjliu** [comment] 2023-02-06 07:54
@bborn do you have an idea of what the issue is?

**Comment by bborn** [comment] 2023-02-06 11:38
@beddows  what's the URL of the feed you're passing it. Looks like the feedparser isn't finding a content element.

**Comment by beddows** [comment] 2023-02-12 16:32
@bborn I'm using the provided links in the notebook, which seem to be valid:

documents = RssReader().load_data([
    "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    "https://roelofjanelsinga.com/atom.xml"
    ])

**Comment by bborn** [comment] 2023-02-12 17:27
@jerryjliu  ok looks like the `content` attribute isn't there for some types of feeds, so we need to check for it in the Dict first. Sent a PR

**Comment by jerryjliu** [comment] 2023-02-20 19:05
Closed with #435

**Closed by jerryjliu** 2023-02-20 19:05 UTC
